### ISSUE TITLE
It might be safer to add a timeout in concurrent api call

### ISSUE THREAD

**Issue by ltebean** [zhongliangjun1/plumber#1]
1. pipeRenderResultQueue
   If any of the threads fails to put a result in it, the `pipeRenderResultQueue.take()` in ControllerInterceptor would wait forever.
2. barrierLatch
   Similarly,  `barrierLatch.await()` will wait forever if any thread fails to execute `latch.countdown()`.

Since if the thread executing the try-catch code is interrupted or killed, the finally block will not execute

**Comment by zhongliangjun1** [comment]
Thanks for the reminding.

In plumber-1.1.1-SNAPSHOT a `response.timeout` configuration has been added to resolve the potentially problems which you mentioned above.

You would be able to see the code adjustment  [here](https://github.com/zhongliangjun1/plumber/commit/84a5257852bc928f80d671e680db6b73a9a0165e).
