### ISSUE TITLE
It could be more convenient to use annotations to indicate whether a pagelet is a barrier or a pipe

### ISSUE THREAD

**Issue by ltebean** [zhongliangjun1/plumber#2]

**Comment by ltebean** [comment]
There is even no need to use an annotation, since pagelet type can be decided when the base view gets parsed('pb-pipe' or 'pb-barrier')

**Comment by zhongliangjun1** [comment]
Now in plumber-1.2.0-SNAPSHOT , a pagelet (barrier or pipe) no longer need to implement the specific interface. Just extending the abstract class of `PlumberPagelet`, plumber will get the pagelet type by parsing the view source('pb-pipe' or 'pb-barrier').

Thanks for the suggestion. And the adjustment of the code is   [here](https://github.com/zhongliangjun1/plumber/compare/84a5257852...d7720fdfdd).
